/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { ZombieFactoryContract } from "./ZombieFactory";
import { KittyInterfaceContract } from "./KittyInterface";
import { ZombieFeedingContract } from "./ZombieFeeding";
import { ZombieHelperContract } from "./ZombieHelper";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Ownable"): OwnableContract;
      require(name: "ZombieFactory"): ZombieFactoryContract;
      require(name: "KittyInterface"): KittyInterfaceContract;
      require(name: "ZombieFeeding"): ZombieFeedingContract;
      require(name: "ZombieHelper"): ZombieHelperContract;
    }
  }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export { ZombieFactoryContract, ZombieFactoryInstance } from "./ZombieFactory";
export {
  KittyInterfaceContract,
  KittyInterfaceInstance,
} from "./KittyInterface";
export { ZombieFeedingContract, ZombieFeedingInstance } from "./ZombieFeeding";
export { ZombieHelperContract, ZombieHelperInstance } from "./ZombieHelper";
